modLoader = "javafml"
loaderVersion = "[5,)"
license = "AGNYA License"
[[mods]]
modId = "various_world"
version = "1.1.1r"
displayName = "Various World"
displayURL = "https://sashakyotoz.github.io/sashakyotoz_dev/"

logoFile = "logo.png"
authors = "SashaKYotoz"

description = '''Across world and its beauty!'''

[[mixins]]
config = "various_world.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
[[dependencies.various_world]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.various_world]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11, 26.1)"
ordering = "NONE"
side = "BOTH"
